
import java.awt.Desktop;
import java.awt.Dimension;
import static java.awt.PageAttributes.MediaType.C;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rishabh
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form AdminMain
     */
    public AdminMain() {
        initComponents();
        setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        try
        {
            //Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sahara", "root", "12345678");
            
            String sql1 = "select * from donee";
            
            PreparedStatement pst1= conn.prepareStatement(sql1);
         
            ResultSet rs1= pst1.executeQuery();
            t1.setModel(DbUtils.resultSetToTableModel(rs1));
            
            
            
            String sql2 = "select * from donor";
            
            PreparedStatement pst2= conn.prepareStatement(sql2);
         
            ResultSet rs2= pst2.executeQuery();
            t2.setModel(DbUtils.resultSetToTableModel(rs2));
            
            
            
            String sql3 = "select * from details";
            
            PreparedStatement pst3= conn.prepareStatement(sql3);
         
            ResultSet rs3= pst3.executeQuery();
            t3.setModel(DbUtils.resultSetToTableModel(rs3));
            
            
            
            String sql4 = "select * from volunteer";
            
            PreparedStatement pst4= conn.prepareStatement(sql4);
         
            ResultSet rs4= pst4.executeQuery();
            t4.setModel(DbUtils.resultSetToTableModel(rs4));
        
           
        }
        catch(Exception e)
        {
             e.printStackTrace();
        }
    }
    public void Export(JTable table, File file){
    try{
        TableModel model = table.getModel();
        FileWriter excel = new FileWriter(file);

        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();

    }catch(IOException e){ System.out.println(e); }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        donee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        donor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        volunteer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        donee1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        export1 = new javax.swing.JButton();
        export4 = new javax.swing.JButton();
        export3 = new javax.swing.JButton();
        export2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        phno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        t3.setForeground(new java.awt.Color(44, 46, 160));
        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(t3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 560, 638, 204);

        t4.setForeground(new java.awt.Color(44, 46, 160));
        t4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(t4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(670, 560, 638, 204);

        t1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(44, 46, 160));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 638, 193);

        t2.setForeground(new java.awt.Color(44, 46, 160));
        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(670, 250, 638, 199);

        donee.setBackground(new java.awt.Color(44, 46, 160));
        donee.setForeground(new java.awt.Color(255, 255, 255));
        donee.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donee details");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/begging.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout doneeLayout = new javax.swing.GroupLayout(donee);
        donee.setLayout(doneeLayout);
        doneeLayout.setHorizontalGroup(
            doneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doneeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        doneeLayout.setVerticalGroup(
            doneeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doneeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(doneeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(donee);
        donee.setBounds(20, 160, 481, 80);

        donor.setBackground(new java.awt.Color(44, 46, 160));
        donor.setForeground(new java.awt.Color(255, 255, 255));
        donor.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Donor details");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        jLabel4.setText("jLabel2");

        javax.swing.GroupLayout donorLayout = new javax.swing.GroupLayout(donor);
        donor.setLayout(donorLayout);
        donorLayout.setHorizontalGroup(
            donorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donorLayout.setVerticalGroup(
            donorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(donorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(donor);
        donor.setBounds(670, 160, 481, 82);

        volunteer.setBackground(new java.awt.Color(44, 46, 160));
        volunteer.setForeground(new java.awt.Color(255, 255, 255));
        volunteer.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Volunteer applications");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/high-five.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        javax.swing.GroupLayout volunteerLayout = new javax.swing.GroupLayout(volunteer);
        volunteer.setLayout(volunteerLayout);
        volunteerLayout.setHorizontalGroup(
            volunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volunteerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        volunteerLayout.setVerticalGroup(
            volunteerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volunteerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(volunteerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(volunteer);
        volunteer.setBounds(670, 470, 476, 82);

        donee1.setBackground(new java.awt.Color(44, 46, 160));
        donee1.setForeground(new java.awt.Color(255, 255, 255));
        donee1.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Donation details");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/donation.png"))); // NOI18N
        jLabel8.setText("jLabel2");

        javax.swing.GroupLayout donee1Layout = new javax.swing.GroupLayout(donee1);
        donee1.setLayout(donee1Layout);
        donee1Layout.setHorizontalGroup(
            donee1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donee1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donee1Layout.setVerticalGroup(
            donee1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donee1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(donee1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(donee1);
        donee1.setBounds(20, 470, 481, 80);

        view.setBackground(new java.awt.Color(36, 37, 130));
        view.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view);
        view.setBounds(420, 60, 110, 50);

        export1.setBackground(new java.awt.Color(36, 37, 130));
        export1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        export1.setForeground(new java.awt.Color(255, 255, 255));
        export1.setText("Export");
        export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export1ActionPerformed(evt);
            }
        });
        jPanel1.add(export1);
        export1.setBounds(510, 160, 151, 80);

        export4.setBackground(new java.awt.Color(36, 37, 130));
        export4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        export4.setForeground(new java.awt.Color(255, 255, 255));
        export4.setText("Export");
        export4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export4ActionPerformed(evt);
            }
        });
        jPanel1.add(export4);
        export4.setBounds(1150, 470, 156, 82);

        export3.setBackground(new java.awt.Color(36, 37, 130));
        export3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        export3.setForeground(new java.awt.Color(255, 255, 255));
        export3.setText("Export");
        export3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export3ActionPerformed(evt);
            }
        });
        jPanel1.add(export3);
        export3.setBounds(510, 470, 151, 80);

        export2.setBackground(new java.awt.Color(36, 37, 130));
        export2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        export2.setForeground(new java.awt.Color(255, 255, 255));
        export2.setText("Export");
        export2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export2ActionPerformed(evt);
            }
        });
        jPanel1.add(export2);
        export2.setBounds(1160, 160, 151, 82);

        jPanel7.setBackground(new java.awt.Color(36, 37, 130));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(150, 120, 220, 3);

        phno.setBackground(new java.awt.Color(255, 255, 255));
        phno.setBorder(null);
        jPanel1.add(phno);
        phno.setBounds(150, 80, 217, 40);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("View details of donee");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 20, 383, 45);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Mobile no.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 80, 123, 30);

        logout.setBackground(new java.awt.Color(36, 37, 130));
        logout.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout.setText(" Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(1130, 20, 180, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export1ActionPerformed
    JFileChooser fc=new JFileChooser(); 
    FileNameExtensionFilter filter = new FileNameExtensionFilter("XLS files", "xls");
    fc.setFileFilter(filter);
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="",s2="";                         
        while((s1=br.readLine())!=null){    
        s2+=s1+"\n";    
        }    
        
        br.close();    
        }catch (Exception ex) { JOptionPane.showMessageDialog(null, "Table exported successfully"); }     
        
        Export(t1,f);
    }
    }//GEN-LAST:event_export1ActionPerformed

    private void export4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export4ActionPerformed
        JFileChooser fc=new JFileChooser(); 
    FileNameExtensionFilter filter = new FileNameExtensionFilter("XLS files", "xls");
    fc.setFileFilter(filter);
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="",s2="";                         
        while((s1=br.readLine())!=null){    
        s2+=s1+"\n";    
        }    
        
        br.close();    
        }catch (Exception ex) { JOptionPane.showMessageDialog(null, "Table exported successfully"); }     
        
        Export(t4,f);
    }
    }//GEN-LAST:event_export4ActionPerformed

    private void export3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export3ActionPerformed
        JFileChooser fc=new JFileChooser(); 
    FileNameExtensionFilter filter = new FileNameExtensionFilter("XLS files", "xls");
    fc.setFileFilter(filter);
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="",s2="";                         
        while((s1=br.readLine())!=null){    
        s2+=s1+"\n";    
        }    
        
        br.close();    
        }catch (Exception ex) { JOptionPane.showMessageDialog(null, "Table exported successfully"); }     
        
        Export(t3,f);
    }
    }//GEN-LAST:event_export3ActionPerformed

    private void export2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export2ActionPerformed
        JFileChooser fc=new JFileChooser(); 
    FileNameExtensionFilter filter = new FileNameExtensionFilter("XLS files", "xls");
    fc.setFileFilter(filter);
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="",s2="";                         
        while((s1=br.readLine())!=null){    
        s2+=s1+"\n";    
        }    
        
        br.close();    
        }catch (Exception ex) { JOptionPane.showMessageDialog(null, "Table exported successfully"); }     
        
        Export(t2,f);
    }
    }//GEN-LAST:event_export2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new AdminLogin();
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        String phno1=phno.getText();
        new AdminView(phno1);
        this.dispose();
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donee;
    private javax.swing.JPanel donee1;
    private javax.swing.JPanel donor;
    private javax.swing.JButton export1;
    private javax.swing.JButton export2;
    private javax.swing.JButton export3;
    private javax.swing.JButton export4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logout;
    private javax.swing.JTextField phno;
    private javax.swing.JTable t1;
    private javax.swing.JTable t2;
    private javax.swing.JTable t3;
    private javax.swing.JTable t4;
    private javax.swing.JButton view;
    private javax.swing.JPanel volunteer;
    // End of variables declaration//GEN-END:variables
}
