
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyEditorManager;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rishabh
 */
public class DoneeForm extends javax.swing.JFrame {
    File f;
    int r=0;
    /**
     * Creates new form DoneeForm
     */
    public DoneeForm() {
        initComponents();
        setVisible(true);
        setSize(700, 1000);   
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        phno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        address = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        family = new javax.swing.JSpinner();
        submit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        choose = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        namelable = new javax.swing.JLabel();
        phlable = new javax.swing.JLabel();
        adlab = new javax.swing.JLabel();
        occupationlabel = new javax.swing.JLabel();
        plab = new javax.swing.JLabel();
        clab = new javax.swing.JLabel();
        file = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 37, 130));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("registeration");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(230, 70, 308, 61);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Donee");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(230, 10, 154, 71);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.png"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 10, 170, 130);

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mobile no.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Aadhar card");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Occupation");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jPanel1.setBackground(new java.awt.Color(36, 37, 130));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 220, -1));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 217, 40));

        jPanel5.setBackground(new java.awt.Color(36, 37, 130));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 220, -1));

        phno.setBackground(new java.awt.Color(255, 255, 255));
        phno.setBorder(null);
        phno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phnoKeyReleased(evt);
            }
        });
        jPanel3.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 217, 40));

        jPanel6.setBackground(new java.awt.Color(36, 37, 130));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, -1));

        jPanel8.setBackground(new java.awt.Color(36, 37, 130));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setBorder(null);
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 217, 40));

        occupation.setBackground(new java.awt.Color(255, 255, 255));
        occupation.setBorder(null);
        occupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationKeyReleased(evt);
            }
        });
        jPanel3.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 217, 40));

        jPanel9.setBackground(new java.awt.Color(36, 37, 130));
        jPanel9.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        family.setModel(new SpinnerNumberModel(1,1,15,1));
        jPanel3.add(family, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, 40));

        submit.setBackground(new java.awt.Color(36, 37, 130));
        submit.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Register");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 190, 60));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("No. of family");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("members");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPanel10.setBackground(new java.awt.Color(36, 37, 130));
        jPanel10.setMinimumSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Confirm");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Password");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        choose.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        choose.setText("Choose file");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        choose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chooseKeyReleased(evt);
            }
        });
        jPanel3.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        back.setBackground(new java.awt.Color(36, 37, 130));
        back.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-arrow.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 70, 60));

        cpass.setBackground(new java.awt.Color(255, 255, 255));
        cpass.setBorder(null);
        cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpassKeyReleased(evt);
            }
        });
        jPanel3.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 220, 40));

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 230, 40));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, -1));

        namelable.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        namelable.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(namelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 110, 20));

        phlable.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        phlable.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(phlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 110, 20));

        adlab.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        adlab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(adlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 110, 20));

        occupationlabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        occupationlabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(occupationlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 100, 20));

        plab.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        plab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(plab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 20));

        clab.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        clab.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(clab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 120, 20));

        file.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        file.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 150, 20));

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 560, 720));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new DoneeLogin();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
       r=1;
        JFileChooser fc=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XLS files", "xls");
        fc.setFileFilter(filter);
        int i=fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION){
            f=fc.getSelectedFile();
            String filepath=f.getPath();
            try{
                BufferedReader br=new BufferedReader(new FileReader(filepath));
                String s1="",s2="";
                while((s1=br.readLine())!=null){
                    s2+=s1+"\n";
                }

                br.close();
            }catch (Exception ex) { JOptionPane.showMessageDialog(null, ""); }
            file.setText(f.getName());
        }
        

    }//GEN-LAST:event_chooseActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        String name1,phno1,address1,family1,occupation1,pass1,cpass1;
        name1=name.getText();
        phno1=phno.getText();
        address1=address.getText();
        family1=family.getValue().toString();
        occupation1=occupation.getText();
        pass1=pass.getText();
        cpass1=cpass.getText();

        // System.out.println(name1+"\n"+phno1+"\n"+address1+"\n"+family1+"\n"+occupation1+"\n"+dropdown1+"\n"+description1+"\n");

        try {
            if(r==0)
            JOptionPane.showMessageDialog(null, "Please add your aadhar card");    
            else if(name1.isEmpty()||phno1.isEmpty()||address1.isEmpty()||family1.isEmpty()||occupation1.isEmpty()||pass1.isEmpty()||cpass1.isEmpty())
            JOptionPane.showMessageDialog(null, "Please make sure all fields are filled in");
            else if(phno1.length()!=10)
            JOptionPane.showMessageDialog(null, "Invalid mobile number");

            else if(pass1.length()<6 || cpass1.length()<6)
            JOptionPane.showMessageDialog(null, "Password shoulld be minimum of 6 characters");
            else if(!pass1.equals(cpass1))
            JOptionPane.showMessageDialog(null, "Passwords don't match");
            else
            {

                try (FileInputStream fin = new FileInputStream(f)) {
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sahara", "root", "12345678");
                    String query="INSERT INTO donee(name,phno,address,family,occupation,pass,aadhar)"+" values ( ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement pst = connection.prepareStatement(query);
                    pst.setString (1, name1);
                    pst.setString (2, phno1);
                    pst.setString (3, address1);
                    pst.setString (4, family1);
                    pst.setString (5, occupation1);
                    pst.setString (6, pass1);
                    pst.setBinaryStream (7, fin, (int) f.length() );

                    int x=pst.executeUpdate();
                    Statement sta = connection.createStatement();

                    if (x == 0) {
                        JOptionPane.showMessageDialog( null, "Already using this mobile no.");

                    } else {
                        JOptionPane.showMessageDialog(null,"Welcome, " + name1 + "\nRegisteration added successfully\nProceed to login.");
                        // System.out.println("Details added successfully");
                        new DoneeLogin();
                        this.dispose();

                    }

                    connection.close();
                } catch (IOException ex) {

                    Logger lgr = Logger.getLogger(DoneeForm.class.getName());
                    lgr.log(Level.SEVERE, ex.getMessage(), ex);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog( ok, "Details already added using this mobile no.");
        }

    }//GEN-LAST:event_submitActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
          String PATTERN="^[a-zA-Z ][ a-zA-Z]{0,15}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(name.getText());
        if(!match.matches())
        {
            namelable.setText("Invalid");
        }
        else
        {
            namelable.setText(null);
        }
    }//GEN-LAST:event_nameKeyReleased

    private void phnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnoKeyReleased
      String PATTERN="^[7-9][0-9]{9}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(phno.getText());
        if(match.matches())
        {
            phlable.setText(null);
        }
        else
        {
            phlable.setText("Invalid");
        }
    }//GEN-LAST:event_phnoKeyReleased

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
         String PATTERN="^[a-zA-Z]{0,30}$";
        Pattern patt= Pattern.compile(PATTERN);
        Matcher match= patt.matcher(address.getText());
        if(!match.matches())
        {
            adlab.setText("Invalid");
        }
        else
        {
            adlab.setText(null);
        }
    }//GEN-LAST:event_addressKeyReleased

    private void occupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occupationKeyReleased
         String PATTERN="^[a-zA-Z]{0,15}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(occupation.getText());
        if(match.matches())
        {
            occupationlabel.setText(null);
        }
        else
        {
            occupationlabel.setText("Enter characters only");
        }
    }//GEN-LAST:event_occupationKeyReleased

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
         String PATTERN="^[a-zA-Z0-9]{0,8}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(pass.getText());
        if(match.matches())
        {
            plab.setText(null);
        }
        else
        {
            plab.setText("Enter only 8 characters/digits");
        }
    }//GEN-LAST:event_passKeyReleased

    private void cpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpassKeyReleased
        if(cpass.getText().equals(pass.getText()))
       {
           clab.setText("Matched");
       }
       else 
       {
           clab.setText("Mismatch");
       }
    }//GEN-LAST:event_cpassKeyReleased

    private void chooseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chooseKeyReleased
//       if(choose.isSelected())
//       {
//           alab.setText(null);
//       }
//       else
//       {
//           alab.setText("Please upload an image");
//       }
    }//GEN-LAST:event_chooseKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel adlab;
    private javax.swing.JButton back;
    private javax.swing.JButton choose;
    private javax.swing.JLabel clab;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JSpinner family;
    private javax.swing.JLabel file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField name;
    private javax.swing.JLabel namelable;
    private javax.swing.JTextField occupation;
    private javax.swing.JLabel occupationlabel;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel phlable;
    private javax.swing.JTextField phno;
    private javax.swing.JLabel plab;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
